"""am adaugat 2 coloane in Incident

Revision ID: fd1a1b003127
Revises: 
Create Date: 2026-07-07 22:59:18.761513

"""
from typing import Sequence, Union
import sqlmodel 
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1a1b003127'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('incident', sa.Column('resolved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident', 'resolved')
    op.drop_column('incident', 'description')
    # ### end Alembic commands ###
